### ISSUE TITLE
Get PDBs with out RNAcentral IDs

### ISSUE THREAD

**Issue by nancyontiveros** [Rfam/rfam-3d-seed-alignments#13] opened 2022-10-11 10:51 UTC
Hi, we need to figure wich PDBs don't have an RNAcentral ID, in a recurrently way for the NEW PDBs added to the families.

Can we collect this information running the script

This is an example in RF00004, 7W5A_H and 7W5B_H among other PDBs don't have RNAcentral IDs
...
7W5A_H
#=GR 7W5A_H 7W5A_H_SS
7W5A_H
#=GR 7W5B_H 7W5B_H_SS
...

**Comment by blakesweeney** [comment] 2022-10-13 10:38
After talking with Nancy this one is actually a duplicate of some other issues. I'm going to close this one and update those.

**Closed by blakesweeney** 2022-10-13 10:38 UTC
